spring:
  application:
    name: order-reactive
logging:
  level:
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    host: "localhost"
    port: "2201"
    database: e-commerce-order
    username: junseok
    password: secret
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: PT30M

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

    # Micrometer 설정 (선택 사항)
    tags:
      application: ${spring.application.name} # 메트릭에 태그 추가
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin 서버 주소
  tracing:
    sampling:
      probability: 1.0 # 샘플링 비율 (1.0 = 모든 요청 추적)

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    com.p6spy.engine.spy.P6SpyDriver: WARN
    p6spy: WARN

---

spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: prod