spring:
  application:
    name: order
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:2201/e-commerce-order"
    username: junseok
    password: secret
  jpa:
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

    # Micrometer 설정 (선택 사항)
    tags:
      application: ${spring.application.name} # 메트릭에 태그 추가

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Zipkin 서버 주소
  tracing:
    sampling:
      probability: 1.0 # 샘플링 비율 (1.0 = 모든 요청 추적)

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    com.p6spy.engine.spy.P6SpyDriver: WARN
    p6spy: WARN

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: prod