spring:
  application:
    name: order
  profiles:
    active: test
  jpa:
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/e-commerce-order"
    username: junseok
    password: secret

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


---

spring:
  config:
    activate:
      on-profile: prod