spring:
  application:
    name: order
  profiles:
    active: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
        use_sql_comments: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.p6spy.engine.spy.P6SpyDriver: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/e-commerce-order"
    username: junseok
    password: secret

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---

spring:
  config:
    activate:
      on-profile: prod