spring:
  application:
    name: core

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      format-sql: true
    show-sql: true
